name: Back End Lint and Build
on: 
  pull_request:
    branches: [ main ]
    paths:  
     - "backend/**"
     - ".github/backend.yml"
  push: 
    paths:  
      - "backend/**"
      - ".github/backend.yml"

jobs: 
  lint: 
    name: Lint Code
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        working-directory: 'backend'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff

      - name: Lint code with Ruff
        run: ruff check --output-format=github --target-version=py39
      
      - name: Check code formatting with Ruff
        run: ruff format --diff --target-version=py39


  build: 
    name: Build
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      
      - name: Install dependencies
        working-directory: 'backend'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy ruff
        
      - name: Run Ruff check
        working-directory: 'backend'
        run: ruff check .

      - name: Run mypy
        working-directory: 'backend'
        run: mypy .

      - name: Import check
        working-directory: 'backend'
        run: python -c "import main"