name: Front End Lint and Build
on: 
  pull_request:
    branches: [ main ]
    paths:  
     - "frontend/**"
     - ".github/frontend.yml"
  push: 
    paths:  
      - "frontend/**"
      - ".github/frontend.yml"

jobs: 
  lint: 
    name: Lint Code
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with: 
          bun-version: "latest"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: "frontend/nodeVersion"

      - name: Install dependecies
        working-directory: 'frontend'
        run: bun install

      - name: Run Lint
        working-directory: 'frontend'
        run: bun run lint


  build:  
    name: Build
    runs-on: ubuntu-latest
    needs: [lint]

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: "frontend/nodeVersion"
      
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with: 
          bun-version: "latest"

      - name: Install dependecies
        working-directory: 'frontend'
        run: bun install

      - name: Build
        working-directory: 'frontend'
        run: bun run build
